name: Run News Crawler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *' # 매일 오전 5시 (KST 기준)

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    env:
      GCP_KEY_BASE64: ${{ secrets.GCP_KEY_BASE64 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 gspread google-auth

      - name: Run crawler
        run: python news_crawler_automation.py
