name: Run News Crawler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'  # 매일 오전 5시 (KST)

jobs:
  crawl:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS_B64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_B64 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 gspread google-auth

      - name: Decode GCP key
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_B64" | base64 -d > service_account.json

      - name: Run crawler
        run: python news_crawler_automation.py
