name: Daily News Crawler

on:
  schedule:
    - cron: '0 16 * * *'   # 매일 KST 새벽 1시
  workflow_dispatch:

jobs:
  run-news-crawler:
    runs-on: self-hosted          # ← 맥 미니 러너

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install requests beautifulsoup4 gspread google-auth

      - name: Decode service-account key
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS_B64" | base64 -d > service_account.json

      - name: Run crawler
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./service_account.json
        run: python news_crawler_automation.py
