name: Run News Crawler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'  # 매일 4AM KST (UTC 기준 19시)

jobs:
  crawl:
    runs-on: ubuntu-latest

    env:
      GCP_KEY_BASE64: ${{ secrets.GCP_KEY_BASE64 }}  # base64로 인코딩된 Google 서비스 키

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 gspread google-auth

      - name: Decode GCP key
        run: |
          echo "$GCP_KEY_BASE64" | base64 -d > service_account.json

      - name: Run crawler
        run: python news_crawler_automation.py
