name: news_crawler.yml

on:
  workflow_dispatch:

jobs:
  run-news-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 gspread google-auth

      - name: Decode service account key from secret
        run: |
          echo "${{ secrets.GCP_KEY_BASE64 }}" | base64 -d > service_account.json

      - name: Run crawler
        run: python news_crawler_automation.py
