name: crawl

on:
  workflow_dispatch:

jobs:
  run-news:
    runs-on: self-hosted      # ← 직접 등록한 Mac mini 러너
    env:
      GOOGLE_APPLICATION_CREDENTIALS_B64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_B64 }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: pip install requests beautifulsoup4 gspread google-auth

      - name: Decode GCP key
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_B64" | base64 -d > service_account.json

      - name: Run crawler
        run: python news_crawler_automation.py
